### ISSUE TITLE
Exceção com tts

### ISSUE THREAD

**Issue by iuriguilherme** [iuriguilherme/iacecil#19]
```
Traceback (most recent call last):
  File "/media/sdd1/iuri/.local/share/virtualenvs/iacecil.0.2-rGDnHZYS/src/iacecil/src/iacecil/controllers/aiogram_bot/bot.py", line 65, in exception_handler
    self.command = await super_function(*args, **kwargs)
  File "/media/sdd1/iuri/.local/share/virtualenvs/iacecil.0.2-rGDnHZYS/lib/python3.10/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)                                                                                    File "/media/sdd1/iuri/.local/share/virtualenvs/iacecil.0.2-rGDnHZYS/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/media/sdd1/iuri/.local/share/virtualenvs/iacecil.0.2-rGDnHZYS/lib/python3.10/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/media/sdd1/iuri/.local/share/virtualenvs/iacecil.0.2-rGDnHZYS/lib/python3.10/site-packages/aiogram/bot/api.py", line 111, in check_result
    raise exceptions.RetryAfter(parameters.retry_after)
aiogram.utils.exceptions.RetryAfter: Flood control exceeded. Retry in 13 seconds.
ERROR:instance.personalidades.pacume:'Voice' object has no attribute 'get'
Traceback (most recent call last):
  File "/media/sdd1/iuri/usr/lib/iacecil.0.2/instance/personalidades/pacume/__init__.py", line 100, in homofobico
    command.voice.get('file_unique_id'),                                                                                                            AttributeError: 'Voice' object has no attribute 'get'
````

**Comment by iuriguilherme** [comment]
Esse atributo está em um objeto do banco de dados, devo ter usado o nome da variável errado ou confundido alguma coisa
